src/utils.js, tests/_utils/utils.js, tests/utils-tests/utils.js, tests/utils.js
=> Added count() method to utils.js.

src/collection.js, tests/collection.js
=> Implemented collection.clear()

src/keyboard.js, tests/keyboard.js
=> Implemented Keyboard util.

src/dom/getdatafromelement.js, src/dom/insertat.js, src/dom/remove.js, src/dom/setdatainelement.js, src/elementreplacer.js, tests/_utils-tests/utils.js, tests/dom/getdatafromelement.html, tests/dom/getdatafromelement.js, tests/dom/setdatainelement.js, tests/elementreplacer.js
=> Moved functions from the core repo.

src/config.js, tests/config.js
Fixes #33 
Related to:
- https://github.com/ckeditor/ckeditor5-creator-classic/pull/4
- https://github.com/ckeditor/ckeditor5/pull/175
=> Refactored configuration class.

src/config.js, tests/config.js
=> Config class does not transform keys in given configuration.

tests/emittermixin.js
A part of https://github.com/ckeditor/ckeditor5-ui/pull/39
=> t/ckeditor5-ui/3: An utility to extend existing templates

src/comparearrays.js, src/diff.js, src/difftochanges.js, tests/comparearrays.js, tests/diff.js, tests/difftochanges.js
Fixes: https://github.com/ckeditor/ckeditor5/issues/211
Related to:
- https://github.com/ckeditor/ckeditor5-undo/pull/20
- https://github.com/ckeditor/ckeditor5-ui-default/pull/32
- https://github.com/ckeditor/ckeditor5-typing/pull/25
- https://github.com/ckeditor/ckeditor5-theme-lark/pull/22
- https://github.com/ckeditor/ckeditor5-engine/pull/530
- https://github.com/ckeditor/ckeditor5-delete/pull/13
- https://github.com/ckeditor/ckeditor5-basic-styles/pull/9
=> Changed const to lower case.

tests/_utils-tests/utils.js, tests/collection.js, tests/observablemixin.js
=> Changed paths and docs to use ckeditor5-core package

src/unicode.js, tests/unicode.js
=> Added: unicode utils.

src/emittermixin.js, src/priorities.js, tests/emittermixin.js, tests/priorities.js
Fixes #55.
Related PR in `engine`: https://github.com/ckeditor/ckeditor5-engine/pull/552
That's all.
=> Added: word priorities for EmitterMixin.

src/emittermixin.js, src/eventinfo.js, tests/emittermixin.js, tests/eventinfo.js
=> t/50b: Implement event delegation mechanism

.jshintrc, src/dom/getdatafromelement.js, src/dom/setdatainelement.js, tests/.jshintrc, tests/dom/createelement.js, tests/dom/getdatafromelement.js, tests/dom/indexof.js, tests/dom/insertat.js, tests/dom/remove.js, tests/dom/setdatainelement.js, tests/elementreplacer.js
=> Turn JSHint browser setting to false.

src/ckeditorerror.js, tests/ckeditorerror.js
Resolves: https://github.com/ckeditor/ckeditor5-utils/issues/2.
=> Added isCKEditorError() static method

tests/collection.js, tests/keyboard.js, tests/observablemixin.js
Fixes: https://github.com/ckeditor/ckeditor5-utils/issues/64.
=> Updated tests with `throwCKEditorError` check

src/normalizehtml.js, tests/normalizehtml.js
Fixes: https://github.com/ckeditor/ckeditor5-utils/issues/19.
=> Created util for normalizing HTML in tests

src/env.js, src/keyboard.js, tests/env.js, tests/keyboard.js
=> t/68: Provided an utility to translate keystroke strings depending on environment

src/emittermixin.js, tests/emittermixin.js
Fixes #76 
Related:
- https://github.com/ckeditor/ckeditor5-ui/issues/79
- https://github.com/ckeditor/ckeditor5-engine/issues/593
- https://github.com/ckeditor/ckeditor5-typing/issues/44
=> Merged EmitterMixin additional parameters into options object.

tests/_utils/locale-mock.js
=> Removed unused method.

tests/dom/getdatafromelement.html, tests/dom/getdatafromelement.js
=> T/92: Removed HTML files from automatic tests

src/collection.js, src/uid.js, tests/collection.js, tests/uid.js
=> t/97: uid() helper yields non–unique values when imported a couple of times

src/dom/emittermixin.js, src/focustracker.js, tests/dom/emittermixin.js
=> DomEmitterMixin was moved from ckeditor5-ui.

src/emittermixin.js, src/eventinfo.js, tests/emittermixin.js
=> t/88: Allowed event rename on delegation and delegation of all events

src/dom/getpositionedancestor.js, src/dom/global.js, src/dom/position.js, src/dom/rect.js, tests/dom/global.js, tests/dom/position.js, tests/dom/rect.js
=> t/108a: 	Implemented global module to create stubbable access to global DOM objects

src/collection.js, tests/collection.js
=> Added getIndex method to Collection class.

src/dom/emittermixin.js, src/emittermixin.js, tests/dom/emittermixin.js, tests/emittermixin.js
=> Changed: Make EmitterMixin#_listeningTo and _emitterId private

src/collection.js
Docs: Remove superfluous items from Collection's constructor jsdoc.
Docs: Remove superfluous items from Collection's constructor jsdoc.
---
=> Docs: Remove superfluous items from Collection's constructor jsdoc.

src/collection.js, tests/collection.js
Other: Imported bindTo method ViewCollection. Closes #125.
=> T/125: Imported bindTo method from ViewCollection

src/first.js, tests/first.js
Feature: Added 'first' function. Closes #130.
=> T/130: Added 'first' function.

src/nth.js, tests/nth.js
Internal: Added tests and docs to the edge cases in the 'nth' function. Closes #137.
=> Added tests and docs to the edge cases in the 'nth' function.

src/dom/rect.js, tests/dom/rect.js
Other: Provided a static `Rect#getDomRangeRects` method for external usage. Closes #168.
=> t/168: Provided a static `Rect#getDomRangeRects` method for external usage

src/keystrokehandler.js, tests/keystrokehandler.js
Feature: KeystrokeHandler should support priorities and proper keystroke canceling. Closes #180.
=> t/ckeditor5/447: KeystrokeHandler should support priorities and proper keystroke canceling

src/collection.js, tests/collection.js
Feature: Introduced `Collection#first` and `Collection#last` getters. Closes #194.
=> Introduced Collection#first and Collection#last getters

tests/_utils-tests/normalizehtml.js
Tests: Aligned tests to changes in view stringify utility. Read more https://githu…b.com/ckeditor/ckeditor5-engine/issues/1179.
---
See: https://github.com/ckeditor/ckeditor5-engine/pull/1184
=> Aligned tests to changes in view stringify utility

src/translation-service.js, tests/translation-service.js
Other: Aligned code to the new Translation Service (ckeditor/ckeditor5#624).
=> Align code to the Translation Service v2

tests/dom/rect.js, tests/dom/scroll.js
Tests: Fixed failed tests on other browsers than Chrome when using BrowserStack. Closes #196.
=> T/196: Fixed tests in order to run on BS

src/observablemixin.js
Internal: Improved docs and implementation of `getBindingTargets` method.
=> Improve docs and implementation of `getBindingTargets` method

src/uid.js, tests/uid.js
Docs: Update utils/uid documentation. Closes #192.
---
* I cannot look longer on the documentation of this method... I've also updated the test to reflect current uid format.
=> Docs: Update utils/uid documentation.

src/translation-service.js
Internal: Fixed CC in `translation-service`. Closes #237.
=> Fix CC in translation-service

LICENSE.md
Internal: Changed the license file structure.
---
=> Changed the license file structure. [skip ci]

src/focustracker.js, tests/focustracker.js
Fix: Made FocusTracker asynchronous. Closes https://github.com/ckeditor/ckeditor5-ui/issues/431.
---
=> Made FocusTracker asynchronous

src/env.js, tests/env.js
Feature: Implmented env#isGecko (see ckeditor/ckeditor5-engine#1439). 
---
Required by https://github.com/ckeditor/ckeditor5-engine/pull/1582.
=> t/ckeditor5-engine/1439: Implmented env#isGecko

docs/framework/guides/deep-dive/observables.md
Docs: Rewritten the "Observables" deep dive guide to use real–life code examples (see #41).
---
A follow-up of https://github.com/ckeditor/ckeditor5-utils/pull/253#discussion_r228469927.
=> t/41b: Rewritten the "Observables" deep dive guide to use real–life code examples

src/collection.js, tests/collection.js
Feature: introduce `Collection.has()` method. Closes #266.
=> 266: Introduce `Collection.has()` method.

docs/framework/guides/deep-dive/observables.md
the param names given dont match those used in the function, I've corrected that.
Type: Message. Closes #000.
---
=> Mismatched values on the view.on example.

package.json
Internal: Added missing dependencies. See ckeditor/ckeditor5#1662.
=> Added missing devDependencies

src/env.js
Docs: Fixed tags for the `env#isGecko` property so that it is listed in the API docs. Closes #286.
=> Fixed API tags for the env#isGecko property

src/env.js, tests/env.js
Feature: Added `env.isAndroid`.
---
Part of https://github.com/ckeditor/ckeditor5-typing/issues/167
=> Added env.isAndroid

tests/locale.js
Tests: Stubbed console warning. Part of ckeditor/ckeditor5#1996.
---
=> Stub console warning

src/dom/createelement.js, tests/dom/createelement.js
Fix: Create valid namespaced elements. Closes #306.
---
* Relates to https://github.com/ckeditor/ckeditor5/issues/1842
=> Allow creating namespaced domelements

package.json, src/version.js
Internal: The version of CKEditor 5 is hardcoded. See ckeditor/ckeditor5#5660.
=> The version of CKEditor 5 is hardcoded

src/version.js
Internal: Added instanbul ignore comments to the "utils/version" module for 100% CC (see ckeditor/ckeditor5#5848).
=> i/5848: Added instanbul ignore comments to the "utils/version" module for 100% CC

tests/dom/getpositionedancestor.js
Tests: Fixed tests leaking editor instances / DOM elements. See ckeditor/ckeditor5#6002.
---
For a complete list of PRs see https://github.com/ckeditor/ckeditor5/issues/6002#issuecomment-567834563.
=> Fixed tests leaking editor instance / DOM element.

tests/_utils/normalizehtml.js
Internal: Adjusted the code to changes required for replacing the `StylesProcessor` singleton with an instance of the class. See ckeditor/ckeditor5#6091.
---
Requires: https://github.com/ckeditor/ckeditor5-engine/pull/1826
=> Adjusted code to changes in i/6091
