src/dom/createelement.js, src/dom/indexof.js, src/dom/insertat.js, src/dom/remove.js, tests/dom/createelement.js, tests/dom/indexof.js, tests/dom/insertat.js, tests/dom/remove.js
=> t/6: Basic DOM utils.

src/keyboard.js, tests/keyboard.js
=> Rename keyboard.keyNames to keyboard.keyCodes

src/observablemixin.js, tests/_utils/utils.js, tests/observablemixin.js
Fixes #47.
Part of https://github.com/ckeditor/ckeditor5-ui-default/issues/25.
=> Allowed ObservableMixin bindings to attributes which don't exist (yet).

tests/unicode.js
Fixes: https://github.com/ckeditor/ckeditor5-utils/issues/66.
Babel was converting Unicode surrogate, `'\uD83D'`, into actual
character. This was incorrect for regexp range test in Safari 9.
=> Fixed compatibility issues in tests

src/unicode.js, tests/unicode.js
=> Fixed: unicode.isInsideSurrogatePair should differentiate between low and high surrogate halves.

src/dom/getpositionedancestor.js, src/dom/isrange.js, src/dom/position.js, src/dom/rect.js, tests/dom/getpositionedancestor.js, tests/dom/isrange.js, tests/dom/position.js, tests/dom/rect.js
=> t/105: Moved rect utilities from BalloonPanelView

src/config.js, tests/config.js
Feature: Added default configuration parameter for `Config`. Closes #126.
---
=> Added default configuration parameter for Config

src/dom/position.js, tests/dom/position.js, tests/manual/position/position.html, tests/manual/position/position.js, tests/manual/position/position.md
Fix: getOptimalPosition() utility does not work when the parent element has a scroll. Closes #139.
=> T/139a: getOptimalPosition() utility does not work when the parent element has a scroll

src/collection.js, tests/collection.js
Feature: Two–way data binding between Collection instances. Closes #132.
=> T/132: Two–way data binding between Collection instances

src/dom/emittermixin.js, tests/dom/emittermixin.js
Fixed: DomEmitterMixin#stopListening should respect listeners attached with useCapture. Closes #146.
=> t/146: DomEmitterMixin#stopListening ignores useCapture.

src/dom/rect.js, tests/dom/rect.js
Fix: Rect utility should work for collapsed DOM Ranges. Closes #153.
=> t/153: Rect utility should work for collapsed DOM Ranges. Closes #153.

src/dom/position.js, tests/dom/position.js
Other: `getOptimalPosition` utility should accept the target option defined as a function. Closes #157.
=> t/157: getOptimalPosition should accept a target defined as a function

src/focustracker.js, tests/focustracker.js
Fix: FocusTracker should remain in sync when multiple 'blur' events are followed by the 'focus'. Closes #159.
=> t/159: FocusTracker should remain in sync when multiple 'blur' events are followed by the 'focus'

src/emittermixin.js, src/eventinfo.js, src/observablemixin.js, tests/emittermixin.js, tests/observablemixin.js
Feature: Introduced `ObservableMixin#decorate()` and support for setting `EmitterMixin#fire()`'s return value by listeners. Closes #162.
=> Introduced ObservableMixin#decorate() and support for fire()'s return values

src/keyboard.js, tests/keyboard.js
Internal: Added support for 'space' key code in parseKeystroke() helper. Closes #169.
=> t/169: Added support for 'space' key code in parseKeystroke() helper

src/dom/rect.js, tests/dom/rect.js
Internal: A warning should show up when a Rect instance is for an HTML element or a DOM range not belonging to a rendered DOM tree. Closes #178.
----
Branches in other repositories to silence the warnings:
* https://github.com/ckeditor/ckeditor5-editor-inline/compare/t/ckeditor5-utils/178
* https://github.com/ckeditor/ckeditor5-ui/compare/t/ckeditor5-utils/178
* https://github.com/ckeditor/ckeditor5-engine/compare/t/ckeditor5-utils/178
=> t/178: A warning should show up when a Rect instance is for an HTML element or a DOM range not belonging to a rendered DOM tree

src/ckeditorerror.js, src/log.js, tests/ckeditorerror.js, tests/log.js
Other: `CKEditorError.message`, `log.error()` and `log.warn()` will contain a link to the documentation. Closes #185.
=> T/185: CKEditorError and logger will contain a link to documentation

src/dom/emittermixin.js, src/emittermixin.js, tests/emittermixin.js
Other: Remove context options form `EmitterMixin` methods: `on`, `once`, `listenTo` and `off`. Closes #77.
BREAKING CHANGE: `EmitterMixin.on` no longer accepts `context` option. Callbacks are now called in `EmitterMixin` instance context. See #77.
BREAKING CHANGE: `EmitterMixin.once` no longer accepts `context` parameter.  Callbacks are now called in `EmitterMixin` instance context. See #77.
BREAKING CHANGE: `EmitterMixin.listenTo` no longer accepts `context` option.   Callbacks are now called in `EmitterMixin`context of emitter instance passed to `listenTo`. See #77.
BREAKING CHANGE: `EmitterMixin.off` no longer accepts `context` option. See #77.
---
*  As usual please give me feedback on this PR message also. I was struggling with either this or merging `BREAKING CHANGE`'s to one …
=> Other: Remove context options form EmitterMixin.

src/ckeditorerror.js, tests/ckeditorerror.js, tests/log.js
Fix: Removed a period at the end of an error message because some browsers included the period in links to errors. Closes #193.
=> Removed a dot at the end of error message.

src/keyboard.js, tests/keyboard.js
Fix: Long keystrokes should be handled properly by getEnvKeystrokeText on Mac. Added support for ⇧ and ⌥ modifiers. Closes #206.
=> t/206: Long keystrokes should be handled properly by getEnvKeystrokeText

src/observablemixin.js, tests/observablemixin.js
Enhancement: Don't throw error when trying to unbind attribute that is not bound. Closes #5.
---
* Small fix I suppose.
=> Don't throw error when trying to unbind attribute that is not bound.

src/locale.js, tests/locale.js
Internal: Changed `Locale#lang` to `Locale#language` to align naming convention.
=> Change `Locale#lang` to `Locale#language` to align naming convention

src/dom/emittermixin.js, src/dom/isdomnode.js, tests/dom/isdomnode.js
Fix: Bulletproofed `isDomNode` helper when used in iframes. Removed `isWindow` logic from the helper. Closes #201.
=> t/201: Bulletproofed isDomNode helper when used in iframes. Removed isWindow logic.

src/dom/emittermixin.js, src/emittermixin.js, tests/dom/emittermixin.js, tests/emittermixin.js
Other: Aligned behaviors of `EmitterMixin` methods responsible for adding end removing listeners. Closes #144.
The `emitter.on` now has the same behavior as `emitter.listenTo( emitter )` as well as `emitter.off` is the same as `emitter.stopListening( emitter )`.
---
* Requires https://github.com/ckeditor/ckeditor5-utils/pull/189 to be closed first as this branch is based on previous work.
* This PR clean up `on`/`listenTo` and `off`/`stopListening` so the `on`/`off` are purely shorthands for base methods.
* I had to make minor changes to internal `Proxy` in `DomEmitterMixin` as it used `listenTo`/`on` in pretty convoluted way. I've renamed `Proxy` methods to not confuse them with `EmitterMixin` ones.
* Only changes besides `EmitterMixin` that were required were in `DomEmitterMixin`.
=> T/144: Refactor EmitterMixin methods.

src/dom/rect.js, tests/dom/rect.js
Fix: Added fallback for `Rect.getDomRangeRects()` if the given range starts in text node. Closes ckeditor/ckeditor5-ui#317.
=> Fix exception that occur after dragging the selection through the image

src/collection.js, tests/collection.js
Feature: Introduced skipping items when binging collections. Closes #215. Closes https://github.com/ckeditor/ckeditor5-ui/issues/92.
=> Feature: Introduced skipping items when binging collections.

src/dom/istext.js, src/dom/rect.js, src/dom/scroll.js, tests/dom/istext.js
Other: Introduced `isText()` helper. Closes #214.
---
PRs in other packages:
- https://github.com/ckeditor/ckeditor5-engine/pull/1259
=> Implement isText() helper

src/dom/emittermixin.js, src/dom/isnode.js, tests/dom/isdomnode.js
Other: Renamed `isDomNode()` to `isNode()`. Closes #219.
BREAKING CHANGE: `isDomNode()` was renamed to `isNode()`.
=> Rename isDomNode() to isNode()

src/env.js, src/keyboard.js, tests/env.js, tests/keyboard.js
Other: Rename `env.mac` to `env.isMac`. Closes #222.
BREAKING CHANGE: Renamed `env.mac` to `env.isMac`.
=> Changed: Rename `env.mac` to `env.isMac`.

src/observablemixin.js, tests/observablemixin.js
Type: Feature: Introduce `bind().toMany()` binding chain in `ObservableMixin`. Closes #224.
=> Feature: Introduce `bind().toMany()` binding chain in `ObservableMixin`.

src/translation-service.js, tests/translation-service.js
Other: Removed `translation-service~add()` function in favor of using safer, always available, manual approach to extending `CKEDITOR_TRANSLATIONS` global. See ckeditor/ckeditor5#914.
BREAKING CHANGES: The `translation-service~add()` function was removed. See `translation-utils` module docs to learn how to add translations.
=> Removed translation-utils's add()

src/fastdiff.js, tests/fastdiff.js
Other: Introduced `fastDiff` diffing function. Closes #235.
---
See #235 for more details.
=> Introduced fastDiff()

src/dom/scroll.js, tests/dom/scroll.js
Fix: Error should not be thrown when scrolling the viewport from within an iframe in a different domain. Closes ckeditor/ckeditor5#930.
---
It is a follow-up of https://github.com/ckeditor/ckeditor5-utils/pull/240/files because I was unable to push to the original PR.  I also simplified the solution and provided a valid test.
As for the cause of the issue, the error is thrown when the child and the parent windows have different domain/ports. In such situation, [for security reasons, `frameElement` is unavailable](https://developer.mozilla.org/en-US/docs/Web/API/Window/frameElement).
If worked for me in my sandbox because I used the same server. JSFiddle uses a different domain for live snippets and hence the error.
=> t/ckeditor5/930: Error should not be thrown when scrolling the viewport from within an iframe in a different domain

src/observablemixin.js, tests/observablemixin.js
Fix: Renamed `beforeChange` event to `set` in the ObservableMixin. Closes #243.
---
- https://github.com/ckeditor/ckeditor5-image/tree/t/ckeditor5-utils/243
- https://github.com/ckeditor/ckeditor5-core/tree/t/ckeditor5-utils/243
```
Internal: Changed `beforeChange` event to `set`.
```
=> Fix: Renamed `beforeChange` event to `set` in the ObservableMixin.

src/focustracker.js, tests/focustracker.js
Fix: Made the `FocusTracker#isFocused` synchronous thanks to `FocusEvent#relatedTarget`. Closes #245.
=> t/245: Made the FocusTracker#isFocused synchronous

src/dom/iswindow.js, tests/dom/iswindow.js
Fix: Fixed `isWindow` helper for the Electron environment. Closes ckeditor/ckeditor5#879.
=> Fix isWindow helper for the Electron environment.

src/env.js, tests/env.js
Feature: Introduce `env.isEdge` property.
---
* Required for:  https://github.com/ckeditor/ckeditor5-widget/pull/46
=> Feature: Add env.isEdge property.

package.json, src/version.js
Feature: Implemented a module exposing the `CKEDIOR_VERSION` to the global scope. Closes ckeditor/ckeditor5#1005.
---
Moved from ckeditor5 (https://github.com/ckeditor/ckeditor5/pull/1140#discussion_r200678841).
* Requires https://github.com/ckeditor/ckeditor5-core/pull/139/files
* CI https://github.com/ckeditor/ckeditor5/tree/t/1005
=> t/ckeditor5/1005: Implemented a module exposing the `CKEDIOR_VERSION` to the global scope

CONTRIBUTING.md, docs/framework/guides/deep-dive/observables.md, src/env.js, src/observablemixin.js, tests/env.js
Docs: Improved documentation of the `Observable#bind` method. Closes #41.
=> t/41: Improved documentation of the `Observable#bind` method

src/ckeditorerror.js, src/collection.js, src/dom/createelement.js, src/dom/getborderwidths.js, src/dom/getpositionedancestor.js, src/dom/position.js, src/emittermixin.js, src/keyboard.js, src/keystrokehandler.js, src/locale.js, src/mapsequal.js
Examples for fixes can be found in `tests/`.
There are some typos I don't know how to fix:
- **KeystrokeInfo**: the properties `altKey`, `ctrlKey` and `shiftKey` are all optional.
- **Options**: the properties `fitInViewport` and `limiter` are all optional.
- **Emitter#delegate**: type for `events` is `...String`.
- **Observable#bind**: type for `bindProperties` is `...String`.
- **Observable#unbind**: type for `unbindProperties` is `...String`.
=> [Docs] Fix some typos

src/config.js, tests/config.js
Feature: Introduce cloning of returned values from Config. Closes #257.
---
* Also changed in repos:
* ckfinder: https://github.com/ckeditor/ckeditor5-ckfinder/tree/t/ckeditor5-utils/257
* heading: https://github.com/ckeditor/ckeditor5-heading/tree/t/ckeditor5-utils/257
* image: https://github.com/ckeditor/ckeditor5-image/tree/t/ckeditor5-utils/257
=> T/257:  Clone returned values from Config.

src/config.js, tests/config.js
Other: DOM Elements will not be cloned when returned from config.get. Closes #264.
---
* @oskarwrobel: please check if the solution works for you.
=> Leave DOM Elements in configuration object returned from editor.config.get().

src/emittermixin.js
Other: Replaced `for..of` statement in `EventEmitter` with `Array.prototype.forEach`. This changes allows building a React application using `create-react-app@2`. Closes ckeditor/ckeditor5-react#40.
=> Replaced `for..of` with `Array.prototype.forEach`

src/emittermixin.js, tests/emittermixin.js
Fix: Prevent infinite loops on `.once()`. Closes #272. Closes #204.
=> Prevent infinite loops on .once()

src/env.js, tests/env.js
Feature: Added `isSafari` property and `isSafari()` function to the `env` module. See: ckeditor/ckeditor5#1463.
---
Required for: https://github.com/ckeditor/ckeditor5-widget/pull/79.
=> Added `isSafari` property to `env` module

src/areconnectedthroughproperties.js, src/ckeditorerror.js, src/collection.js, src/focustracker.js, src/keyboard.js, src/observablemixin.js, tests/_utils-tests/utils.js, tests/_utils/utils.js, tests/areconnectedthroughproperties.js, tests/ckeditorerror.js, tests/collection.js, tests/focustracker.js, tests/keyboard.js, tests/observablemixin.js
Other: Added context as second required argument to the `CKEditorError`'s constructor, changed `isCKEditorError()` method to `is()`. Introduced the `areConnectedThroughProperties()` utility Part of the ckeditor/ckeditor5-watchdog#1.
---
* The added context is required by the Watchdog feature which will be trying to determine which editor crashed in order to restart the proper one. The context might include the editor instance some deep in the JS structure (including objects, array, maps, etc) or the context might be a part accessible from the editor (like `editor.model`, etc.)
* The old `CKEditorError.isCKEditorError()` method was changed to `CKEditorError.is()` and no longer uses the `instanceof` check.
=> Add context to `CKEditorError`, change `isCKEditorError()` to `is()`, introduce the `areConnectedThroughProperties()` util

src/dom/rect.js, tests/dom/rect.js, tests/dom/scroll.js
Fix: `Rect#excludeScrollbarsAndBorders` should support RTL environments. Fixed incorrect output of the method. Closes #297.
=> t/297: Fix: `Rect#excludeScrollbarsAndBorders` should support RTL content

package.json, tests/_utils-tests/utils.js, tests/_utils/utils.js
Feature: Introduce `assertEqualMarkup()` test util method. Closes ckeditor/ckeditor5-paste-from-office#14.
---
* ~I'll check if we can use it somewhere else other then PFO - tables?~
* 2 New dev dependencies:
- 1. js-beautify for formatting HTML code: https://www.npmjs.com/package/js-beautify
- 2. assertion-error for throwing chai compatible assertion errors (already added by chai from the testing environment).
Required by https://github.com/ckeditor/ckeditor5-engine/pull/1779
=> Introduce assertEqualMarkup() test util

src/ckeditorerror.js, src/emittermixin.js, tests/ckeditorerror.js, tests/emittermixin.js
Other: Introduced the `CKEditorError.rethrowUnexpectedError()` helper. Added custom error handling for the `Emitter#fire()` function. Part of ckeditor/ckeditor5#1304.
---
=> Introduced `CKEditorError.rethrowUnexpectedError()`. Add custom error handling.

src/ckeditorerror.js, src/emittermixin.js, tests/ckeditorerror.js, tests/emittermixin.js
Fix: Improved error rethrowing by replacing the error stack. Closes ckeditor/ckeditor5#5595.
---
Requires:
- https://github.com/ckeditor/ckeditor5-engine/pull/1810
- https://github.com/ckeditor/ckeditor5-core/pull/202
- https://github.com/ckeditor/ckeditor5-image/pull/336
- https://github.com/ckeditor/ckeditor5-watchdog/pull/30
=> Improve error rethrowing by replacing the error stack

src/config.js, tests/config.js
Feature: Added iterator interface to the `Config` class. Part of ckeditor/ckeditor5#5891.
---
Required by the https://github.com/ckeditor/ckeditor5-core/pull/204. `Editor#config` needs to be extended by the `Context#config`.
=> Added iterator interface to the Config class.

tests/_utils-tests/normalizehtml.js
Tests: Align tests to the changes in style normalization.
---
Sub-pr for: https://github.com/ckeditor/ckeditor5-engine/pull/1807.
* I've used safer `padding` style instead of the `border` which is output as `border-top, -right,`etc.
=> Use other style in normalizeHtml tests.

src/uid.js
Internal: The `uid()` helper should be a lot faster. Closes ckeditor/ckeditor5#6188.
=> i/6188: The `uid()` helper should be a lot faster

src/objecttomap.js, src/tomap.js
Other: Improved `toMap` method performance. This results with improved editor data processing speed. Closes ckeditor/ckeditor5#5854.
---
lodash' `isPlainObject` is a pretty performance expensive function, so should be avoided in places that are called frequently. This PR reverses the condition so a cheaper and more common condition is used first.
Alternatively we could create our own, more optimized `isPlainObject` implementation, but since our code uses iterables for the most part here, it's enough to just reverse the condition check.
You can use manual tests added in ckeditor/ckeditor5#5880 to have use performance tests.
There's a sub pr for this: ckeditor/ckeditor5-engine#1822.
| test case | total time (ms/%) | PR total time (ms/%) | total click handler time | PR total click handler …
=> Used a cheaper type check in toMap function, to improve performance

src/config.js, tests/config.js
Internal: Introduced copying default configuration in the `Config` class to make the watchdog feature work correctly. Part of ckeditor/ckeditor5#6219.
---
=> Introduced copying default configuration in the `Config` class to make the watchdog feature work correctly

src/collection.js, tests/collection.js
Feature: Added support for initializing `Collection` items using a constructor. Closes ckeditor/ckeditor5#6319.
---
This PR was mostly based on #309 with some notable changes:
*   Reverted `collection-add-invalid-id` and `collection-add-item-already-exists` error interfaces back to what we have on the `master` branch (see [current](6f51d49026045ef9919cccab68eeeee736c4c7ac) vs [originally proposed](https://github.com/ckeditor/ckeditor5-utils/blob/1aac49db1ca9ea914f9fc44f00e295474faf3ed2/src/collection.js#L669-L693)). I don't think there's a strong reason to change this API.
*   `add()` remains unchanged with exception of reusing `_getItemIdBeforeAdding()`.
*   Added API docs.
*   Added couple more test cases: `generates id for items that doesn\'t have it`, `throws an error when invalid …
=> Added support for initializing Collection using a constructor

src/observablemixin.js
Fix: Editor will now load correctly in environment with `Symbol` polyfilled. Closes ckeditor/ckeditor5#6489.
=> Fix editor loading when using Symbol polyfill

src/fastdiff.js, tests/diff.js, tests/fastdiff.js
Fix: Fixed fastDiff for multi-byte unicode sequences. Closes ckeditor/ckeditor5#3147. Closes ckeditor/ckeditor5#6495.
---
* ckeditor/ckeditor5-typing#228
=> Fixed fastDiff for multi-byte unicode sequences.

src/focustracker.js
Docs: Linked to the "Deep dive into focus tracking" from the FocusTracker class docs (see ckeditor/ckeditor5#6087).
---
Part of https://github.com/ckeditor/ckeditor5-ui/pull/552.
=> i/6087: Linked to the "Deep dive into focus tracking" from the FocusTracker class docs

src/dom/resizeobserver.js, tests/dom/resizeobserver.js
Fix: Do not execute `ResizeObserver` callbacks when the resized element is invisible. Closes ckeditor/ckeditor5#6570.
=> i/6570: Do not execute `ResizeObserver` callbacks when the resized element is invisible

src/dom/getpositionedancestor.js, src/dom/position.js, tests/dom/getpositionedancestor.js, tests/dom/position.js
Other: The `getPositionedAncestor()` helper should use `offsetParent` instead of `getComputedStyle()` for performance reasons. Closes ckeditor/ckeditor5#6573.
MINOR BREAKING CHANGE: The `getPositionedAncestor()` helper will no longer return the passed element when it is positioned. 
---
**When closed, it must be followed by an update and a [merge](https://github.com/cksource/ckeditor5-comments/pull/187) in the comments plugin.**
**An important notice: The `getPositionedAncestor()` helper is used only by the `getOptimalPosition()` helper at this moment.**
OK, so here's what happened in this PR:
1. I used `offsetParent` instead of `getComputedStyle()`, which results in a massive performance gain. This is how old vs new implementation performs when executed 100 times on a DOM tree of 100 …
=> i/6573: The `getPositionedAncestor()` helper should use `offsetParent` instead of `getComputedStyle()`

src/env.js, tests/env.js
Remove some special cases for Edge, as since it's Chromium-based now, it behaves closer to others.
BREAKING CHANGE: `env.isEdge` is no longer available in utils API, see #6202.
Other: Remove `env.isEdge`. Closes ckeditor/ckeditor5#6202.
Remove some special cases for Edge, as since it's Chromium-based now, it behaves closer to others.
---
I removed all occurrences of `env.isEdge` and tests for specific behavior in case of its presence. 
Run `npm run test` for Firefox, Chrome. I didn't find any manual tests related to it, so I just check a few random ones.
I was not sure, whether I should touch 
1. https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/domconverter.js#L172 
Was the initial, non-Edge/pre-Edge16 intent to use 
`domElement.childNodes.forEach`? …
=> Other: Remove `env.isEdge`. Closes ckeditor/ckeditor5#6202.

src/locale.js, src/translation-service.js, tests/locale.js, tests/translation-service.js
Feature: Provided support for plural forms internalization. Part of ckeditor/ckeditor5#6526.
MINOR BREAKING CHANGE: The `translate` function from the `translation-service` was marked as protected. See #334.
MINOR BREAKING CHANGE: The format of translations added to the editor has been changed. If you use `window.CKEDITOR_TRANSLATIONS` please see #334.
---
The `translate` function in the `translation-service` was marked as protected and renamed to `_translate`. All features depending on the translation mechanism should use the `Locale#t()` function instead.
The new format of the  `window.CKEDITOR_TRANSLATIONS`:
```js
{
pl: {
dictionary: {
'Cancel': 'Anuluj',
'Add space': [ 'Dodaj spację', 'Dodaj %0 spacje', 'Dodaj %0 spacji' ]
}, 
// A function that returns the plural form index.
// …
```
=> Provide support for translating plural forms
